# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('test1', models.FloatField(default=0)),
                ('test2', models.FloatField(default=0)),
                ('test3', models.IntegerField(default=0)),
            ],
        ),
    ]
